# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_param chipscope.maxJobs 4
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/quantum/Documents/Oakland_university/Fall_2021/ECE5710/ECE5710_Final_Project/loon_bounce/ECE5710_final.cache/wt [current_project]
set_property parent.project_path /home/quantum/Documents/Oakland_university/Fall_2021/ECE5710/ECE5710_Final_Project/loon_bounce/ECE5710_final.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo /home/quantum/Documents/Oakland_university/Fall_2021/ECE5710/ECE5710_Final_Project/loon_bounce/ECE5710_final.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files /home/quantum/Documents/Oakland_university/Fall_2021/ECE5710/ECE5710_Final_Project/resources/ball.coe
read_mem {{/home/quantum/Documents/Oakland_university/Fall_2021/ECE5710/ECE5710_Final_Project/loon_bounce/ECE5710_final.srcs/sources_1/imports/Example 6/loons240x160.mif}}
read_vhdl -library xil_defaultlib {
  {/home/quantum/Documents/Oakland_university/Fall_2021/ECE5710/ECE5710_Final_Project/loon_bounce/ECE5710_final.srcs/sources_1/imports/Example 6/bounce.vhd}
  {/home/quantum/Documents/Oakland_university/Fall_2021/ECE5710/ECE5710_Final_Project/loon_bounce/ECE5710_final.srcs/sources_1/imports/Example 6/clkdiv2.vhd}
  {/home/quantum/Documents/Oakland_university/Fall_2021/ECE5710/ECE5710_Final_Project/loon_bounce/ECE5710_final.srcs/sources_1/imports/Example 6/clock_pulse.vhd}
  {/home/quantum/Documents/Oakland_university/Fall_2021/ECE5710/ECE5710_Final_Project/loon_bounce/ECE5710_final.srcs/sources_1/imports/Example 6/vga_640x480.vhd}
  {/home/quantum/Documents/Oakland_university/Fall_2021/ECE5710/ECE5710_Final_Project/loon_bounce/ECE5710_final.srcs/sources_1/imports/Example 6/vga_ScreenSaver.vhd}
  {/home/quantum/Documents/Oakland_university/Fall_2021/ECE5710/ECE5710_Final_Project/loon_bounce/ECE5710_final.srcs/sources_1/imports/Example 6/vga_components.vhd}
  {/home/quantum/Documents/Oakland_university/Fall_2021/ECE5710/ECE5710_Final_Project/loon_bounce/ECE5710_final.srcs/sources_1/imports/Example 6/vga_ScreenSaver_top.vhd}
}
read_ip -quiet /home/quantum/Documents/Oakland_university/Fall_2021/ECE5710/ECE5710_Final_Project/loon_bounce/ECE5710_final.srcs/sources_1/ip/x8ball_ROM/x8ball_ROM.xci
set_property used_in_implementation false [get_files -all /home/quantum/Documents/Oakland_university/Fall_2021/ECE5710/ECE5710_Final_Project/loon_bounce/ECE5710_final.srcs/sources_1/ip/x8ball_ROM/x8ball_ROM_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/quantum/Documents/Oakland_university/Fall_2021/ECE5710/ECE5710_Final_Project/loon_bounce/ECE5710_final.srcs/constrs_1/imports/ECE5710/nexys4_ddr.xdc
set_property used_in_implementation false [get_files /home/quantum/Documents/Oakland_university/Fall_2021/ECE5710/ECE5710_Final_Project/loon_bounce/ECE5710_final.srcs/constrs_1/imports/ECE5710/nexys4_ddr.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top vga_ScreenSaver_top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef vga_ScreenSaver_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file vga_ScreenSaver_top_utilization_synth.rpt -pb vga_ScreenSaver_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
