# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Quantum/Documents/Oakland University/Fall 2021/ECE5710/ECE5710_Final_Project/platform_100t_v3/platform_100t.srcs/sources_1/ip/DPRAM/DPRAM.xci
# IP: The module: 'DPRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Quantum/Documents/Oakland University/Fall 2021/ECE5710/ECE5710_Final_Project/platform_100t_v3/platform_100t.srcs/sources_1/ip/DPRAM/DPRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DPRAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/Quantum/Documents/Oakland University/Fall 2021/ECE5710/ECE5710_Final_Project/platform_100t_v3/platform_100t.srcs/sources_1/ip/DPRAM/DPRAM.xci
# IP: The module: 'DPRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Quantum/Documents/Oakland University/Fall 2021/ECE5710/ECE5710_Final_Project/platform_100t_v3/platform_100t.srcs/sources_1/ip/DPRAM/DPRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DPRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
