# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/ECE5710_Final_Project/nexys4_ddr.xdc

# IP: ip/platformROM/platformROM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==platformROM || ORIG_REF_NAME==platformROM} -quiet] -quiet
