# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/ECE5710_Final_Project/nexys4_ddr.xdc

# IP: ip/x8ball_ROM/x8ball_ROM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==x8ball_ROM || ORIG_REF_NAME==x8ball_ROM} -quiet] -quiet

# IP: ip/platformROM/platformROM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==platformROM || ORIG_REF_NAME==platformROM} -quiet] -quiet

# IP: ip/blk_mem_gen_3/blk_mem_gen_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_3 || ORIG_REF_NAME==blk_mem_gen_3} -quiet] -quiet

# IP: ip/blk_mem_gen_2/blk_mem_gen_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_2 || ORIG_REF_NAME==blk_mem_gen_2} -quiet] -quiet

# IP: ip/blk_mem_gen_1/blk_mem_gen_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_1 || ORIG_REF_NAME==blk_mem_gen_1} -quiet] -quiet

# IP: ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==blk_mem_gen_0 || ORIG_REF_NAME==blk_mem_gen_0} -quiet] -quiet
