# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/quantum/Documents/Oakland_university/Fall_2021/ECE5710/ECE5710_Final_Project/platform_ball_wall_block_backgroundMusic/platform_100t_v3/platform_100t.srcs/sources_1/ip/x8ball_ROM/x8ball_ROM.xci
# IP: The module: 'x8ball_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/quantum/Documents/Oakland_university/Fall_2021/ECE5710/ECE5710_Final_Project/platform_ball_wall_block_backgroundMusic/platform_100t_v3/platform_100t.srcs/sources_1/ip/x8ball_ROM/x8ball_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'x8ball_ROM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/quantum/Documents/Oakland_university/Fall_2021/ECE5710/ECE5710_Final_Project/platform_ball_wall_block_backgroundMusic/platform_100t_v3/platform_100t.srcs/sources_1/ip/x8ball_ROM/x8ball_ROM.xci
# IP: The module: 'x8ball_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/quantum/Documents/Oakland_university/Fall_2021/ECE5710/ECE5710_Final_Project/platform_ball_wall_block_backgroundMusic/platform_100t_v3/platform_100t.srcs/sources_1/ip/x8ball_ROM/x8ball_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'x8ball_ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
