# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/quantum/Documents/Oakland_university/Fall_2021/ECE5710/ECE5710_Final_Project/ver6-20211213T044435Z-001/ver6/final_project/final_project.srcs/sources_1/ip/dpram_1/dpram.xci
# IP: The module: 'dpram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/quantum/Documents/Oakland_university/Fall_2021/ECE5710/ECE5710_Final_Project/ver6-20211213T044435Z-001/ver6/final_project/final_project.srcs/sources_1/ip/dpram_1/dpram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/quantum/Documents/Oakland_university/Fall_2021/ECE5710/ECE5710_Final_Project/ver6-20211213T044435Z-001/ver6/final_project/final_project.srcs/sources_1/ip/dpram_1/dpram.xci
# IP: The module: 'dpram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/quantum/Documents/Oakland_university/Fall_2021/ECE5710/ECE5710_Final_Project/ver6-20211213T044435Z-001/ver6/final_project/final_project.srcs/sources_1/ip/dpram_1/dpram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
