# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/quantum/Documents/Oakland_university/Fall_2021/ECE5710/ECE5710_Final_Project/platform_100t_v3/platform_100t.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4.xci
# IP: The module: 'blk_mem_gen_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/quantum/Documents/Oakland_university/Fall_2021/ECE5710/ECE5710_Final_Project/platform_100t_v3/platform_100t.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_4'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/quantum/Documents/Oakland_university/Fall_2021/ECE5710/ECE5710_Final_Project/platform_100t_v3/platform_100t.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4.xci
# IP: The module: 'blk_mem_gen_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/quantum/Documents/Oakland_university/Fall_2021/ECE5710/ECE5710_Final_Project/platform_100t_v3/platform_100t.srcs/sources_1/ip/blk_mem_gen_4/blk_mem_gen_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
