# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Dima/OneDrive/Documents/ECE4710/project/platform/platform/platform.srcs/sources_1/ip/lives/lives.xci
# IP: The module: 'lives' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dima/OneDrive/Documents/ECE4710/project/platform/platform/platform.srcs/sources_1/ip/lives/lives_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lives'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Dima/OneDrive/Documents/ECE4710/project/platform/platform/platform.srcs/sources_1/ip/lives/lives.xci
# IP: The module: 'lives' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Dima/OneDrive/Documents/ECE4710/project/platform/platform/platform.srcs/sources_1/ip/lives/lives_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lives'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
